use std::{env, error::Error, fs, path::PathBuf};

const SLINT_ENTRY: &str = "assets/slint/all.slint";
const TR_SLINT: &str = "assets/slint/tr.slint";

fn main() -> Result<(), Box<dyn Error>> {
    for path in glob::glob("assets/slint/**/*.slint")?.filter_map(Result::ok) {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    slint_build::compile(SLINT_ENTRY)?;

    generate_tr_setters()?;

    Ok(())
}

fn generate_tr_setters() -> Result<(), Box<dyn Error>> {
    let tr_source = fs::read_to_string(TR_SLINT)?;
    let properties = parse_tr_properties(&tr_source);

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from assets/slint/tr.slint. Do not edit.\n\n");
    out.push_str("#[allow(clippy::type_complexity)]\n");
    out.push_str("pub const TR_SETTERS: &[(&str, fn(&Tr<'_>, ::slint::SharedString))] = &[\n");
    for name in &properties {
        let setter = format!("set_{}", name.replace('-', "_"));
        out.push_str(&format!("    (\"{name}\", |tr, v| tr.{setter}(v)),\n"));
    }
    out.push_str("];\n\n");
    out.push_str("pub fn apply_translations(tr: &Tr<'_>) {\n");
    out.push_str("    for (key, setter) in TR_SETTERS {\n");
    out.push_str("        setter(tr, ::i18n::translate(key).into());\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(out_dir.join("tr_setters.rs"), out)?;
    Ok(())
}

fn parse_tr_properties(source: &str) -> Vec<String> {
    const PREFIX: &str = "in property <string>";
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let rest = line.strip_prefix(PREFIX)?.trim_start();
            let name_end = rest.find(|c: char| c == ':' || c.is_whitespace())?;
            Some(rest[..name_end].to_string())
        })
        .collect()
}
